Repository Terasology/Health, pull requests merged in 2021-08, with the labels that each got.

#96 fix: only render damage overlay on client receiving damage
  src/main/java/org/terasology/module/health/systems/HealthClientSystem.java
Labels: Type: Bug

#93 chore: overhaul the block damage system
  src/main/java/org/terasology/module/health/systems/BlockDamageAuthoritySystem.java
  src/main/java/org/terasology/module/health/systems/BlockDamageRenderer.java
  src/main/java/org/terasology/module/health/systems/DamageEffectAuthoritySystem.java
Labels: Category: Doc, Multiplayer, Topic: Stabilization, Status: Needs Testing, Type: Chore

#94 chore: adjust for changes to BlockPart
  src/main/java/org/terasology/module/health/systems/BlockDamageAuthoritySystem.java
  src/main/java/org/terasology/module/health/systems/DamageEffectAuthoritySystem.java
Labels: Type: Chore
