Repository Terasology/Health, pull requests merged in 2021-05, with the labels that each got.

#84 feat!: overhaul regeneration logic
  deltas/engine/prefabs/player/player.prefab
  src/main/java/org/terasology/module/health/components/HealthComponent.java
  src/main/java/org/terasology/module/health/components/RegenComponent.java
  src/main/java/org/terasology/module/health/core/BaseRegenAuthoritySystem.java
  src/main/java/org/terasology/module/health/core/BaseRegenComponent.java
  src/main/java/org/terasology/module/health/core/CoreHealthSystem.java
  src/main/java/org/terasology/module/health/events/ActivateRegenEvent.java
  src/main/java/org/terasology/module/health/systems/BlockDamageAuthoritySystem.java
  src/main/java/org/terasology/module/health/systems/DamageAuthoritySystem.java
  src/main/java/org/terasology/module/health/systems/HealthCommands.java
  src/main/java/org/terasology/module/health/systems/RegenAuthoritySystem.java
  src/main/java/org/terasology/module/health/time/Duration.java
  src/main/java/org/terasology/module/health/time/DurationTypeHandler.java
  src/main/java/org/terasology/module/health/time/Instant.java
  src/main/java/org/terasology/module/health/time/InstantTypeHandler.java
  src/test/java/org/terasology/module/health/systems/RegenTest.java
Labels: enhancement

#88 refactor!: overhaul events
  src/main/java/org/terasology/module/health/components/RegenComponent.java
  src/main/java/org/terasology/module/health/core/BaseRegenAuthoritySystem.java
  src/main/java/org/terasology/module/health/events/ActivateRegenEvent.java
  src/main/java/org/terasology/module/health/events/BeforeRegenEvent.java
  src/main/java/org/terasology/module/health/events/BeforeRestoreEvent.java
  src/main/java/org/terasology/module/health/events/DeactivateRegenEvent.java
  src/main/java/org/terasology/module/health/events/DeregisterRegenEvent.java
  src/main/java/org/terasology/module/health/events/DoRestoreEvent.java
  src/main/java/org/terasology/module/health/events/MaxHealthChangedEvent.java
  src/main/java/org/terasology/module/health/events/OnDamagedEvent.java
  src/main/java/org/terasology/module/health/events/OnRestoredEvent.java
  src/main/java/org/terasology/module/health/events/RegisterRegenEvent.java
  src/main/java/org/terasology/module/health/systems/HealthCommands.java
  src/main/java/org/terasology/module/health/systems/RegenAuthoritySystem.java
  src/main/java/org/terasology/module/health/systems/RestorationAuthoritySystem.java
  src/test/java/org/terasology/module/health/systems/RegenTest.java
Labels: enhancement

#90 style: fix checkstyle findings
  src/main/java/org/terasology/module/health/components/DamageResistComponent.java
  src/main/java/org/terasology/module/health/core/BaseRegenAuthoritySystem.java
  src/main/java/org/terasology/module/health/systems/BlockDamageAuthoritySystem.java
  src/main/java/org/terasology/module/health/systems/HealthCommands.java
  src/main/java/org/terasology/module/health/systems/RegenAuthoritySystem.java
  src/test/java/org/terasology/module/health/BlockTest.java
  src/test/java/org/terasology/module/health/RestorationTest.java
  src/test/java/org/terasology/module/health/systems/BlockDamageRendererTest.java
  src/test/java/org/terasology/module/health/systems/HealthClientSystemTest.java
  src/test/java/org/terasology/module/health/systems/RegenTest.java
Labels: Category: Test/QA, Type: Chore

#89 style: fix static analysis reports (checkstyle, spotbugs, pmd)
  src/main/java/org/terasology/module/health/components/DamageResistComponent.java
  src/main/java/org/terasology/module/health/systems/BlockDamageAuthoritySystem.java
  src/main/java/org/terasology/module/health/systems/DamageAuthoritySystem.java
  src/main/java/org/terasology/module/health/systems/HealthCommands.java
  src/main/java/org/terasology/module/health/systems/RegenAuthoritySystem.java
  src/test/java/org/terasology/module/health/BlockTest.java
  src/test/java/org/terasology/module/health/DamageEventTest.java
  src/test/java/org/terasology/module/health/systems/RegenTest.java
Labels: Topic: Stabilization, Type: Chore

#91 refactor: play damage sounds
  src/main/java/org/terasology/module/health/systems/BlockDamageAuthoritySystem.java
  src/main/java/org/terasology/module/health/systems/DamageAuthoritySystem.java
Labels: Status: Needs Testing, Topic: Stabilization, Type: Chore
